##36.	Write code to capture network traffic generated by a webpage using Selenium WebDriver in Python.
from selenium.webdriver.chrome.service import Service
from seleniumwire import webdriver

##chrome driver
driver = webdriver.Chrome(service=Service('../driver/chromedriver.exe'))
driver.maximize_window()
##website
driver.get("https://rahulshettyacademy.com/AutomationPractice/")
network_error_list=[]

for request in driver.requests:
    if request.response.status_code>=200:
        network_error_list.append(request.url)
    print(network_error_list)
driver.quit()